package com.travel.ai.task;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.lang.management.ManagementFactory;
import java.net.InetAddress;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Component
public class AgentTaskWorker {

    private static final Logger log = LoggerFactory.getLogger(AgentTaskWorker.class);

    private final AgentTaskJdbcRepository repository;
    private final AgentTaskProperties properties;
    private final ObjectMapper objectMapper;
    private final String workerId;

    public AgentTaskWorker(
            AgentTaskJdbcRepository repository,
            AgentTaskProperties properties,
            ObjectMapper objectMapper) {
        this.repository = repository;
        this.properties = properties;
        this.objectMapper = objectMapper;
        this.workerId = buildWorkerId();
    }

    @Scheduled(fixedDelayString = "${app.agent-task.worker.fixed-delay:2000}")
    public void tick() {
        if (!properties.getWorker().isEnabled()) {
            return;
        }
        try {
            int recovered = repository.recoverExpiredLeases();
            if (recovered > 0) {
                log.info("[agent-task] recovered_expired_leases count={}", recovered);
            }
            List<AgentTaskRow> tasks = repository.claimDueTasks(
                    workerId,
                    properties.getWorker().getLeaseSeconds(),
                    properties.getWorker().getBatchSize());
            for (AgentTaskRow task : tasks) {
                runOne(task);
            }
        } catch (Exception e) {
            log.warn("[agent-task] worker_tick_failed err={}", e.toString());
        }
    }

    private void runOne(AgentTaskRow task) {
        try {
            if (task.taskType() != AgentTaskType.ANALYSIS_REPORT_MOCK) {
                throw new IllegalArgumentException("unsupported task_type: " + task.taskType());
            }
            ObjectNode result = objectMapper.createObjectNode();
            result.put("report_type", AgentTaskType.ANALYSIS_REPORT_MOCK.name());
            result.put("title", "Mock Financial Analysis Report");
            result.put("summary", "This is a mock async report generated by Async Agent Task V1.");
            result.set("input_payload", task.payload());
            result.put("generated_at", Instant.now().toString());
            result.put("non_investment_advice", true);
            result.put("risk_disclaimer", "仅供研究和教育参考，不构成投资建议。");
            result.put("mock_data", true);
            result.put("real_financial_api_used", false);
            result.put("trading_capability_used", false);
            repository.markSucceeded(task.taskId(), result);
            log.info("[agent-task] task_succeeded taskId={} type={}", task.taskId(), task.taskType());
        } catch (Exception e) {
            repository.markFailedOrRetry(task.taskId(), e.toString());
            log.warn("[agent-task] task_failed_or_retry taskId={} err={}", task.taskId(), e.toString());
        }
    }

    private static String buildWorkerId() {
        String host = "unknown";
        try {
            host = InetAddress.getLocalHost().getHostName();
        } catch (Exception ignored) {
        }
        return host + ":" + ManagementFactory.getRuntimeMXBean().getName() + ":" + UUID.randomUUID();
    }
}

