package com.travel.ai.task;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.slf4j.MDC;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.lang.management.ManagementFactory;
import java.net.InetAddress;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Component
public class AgentTaskWorker {

    private static final Logger log = LoggerFactory.getLogger(AgentTaskWorker.class);

    private final AgentTaskJdbcRepository repository;
    private final AgentTaskProperties properties;
    private final ObjectMapper objectMapper;
    private final String workerId;

    public AgentTaskWorker(
            AgentTaskJdbcRepository repository,
            AgentTaskProperties properties,
            ObjectMapper objectMapper) {
        this.repository = repository;
        this.properties = properties;
        this.objectMapper = objectMapper;
        this.workerId = buildWorkerId();
    }

    @Scheduled(fixedDelayString = "${app.agent-task.worker.fixed-delay:2000}")
    public void tick() {
        if (!properties.getWorker().isEnabled()) {
            return;
        }
        try {
            List<AgentTaskRow> recovered = repository.recoverExpiredLeases(workerId);
            if (!recovered.isEmpty()) {
                for (AgentTaskRow row : recovered) {
                    log.info("[agent-task] event=lease_recovered task_id={} request_id={} worker_id={} task_type={} status={} retry_count={} latency_ms=0",
                            row.taskId(), row.requestId(), workerId, row.taskType(), row.status(), row.retryCount());
                }
            }
            List<AgentTaskRow> tasks = repository.claimDueTasks(
                    workerId,
                    properties.getWorker().getLeaseSeconds(),
                    properties.getWorker().getBatchSize());
            for (AgentTaskRow task : tasks) {
                log.info("[agent-task] event=task_claimed task_id={} request_id={} worker_id={} task_type={} status={} retry_count={} latency_ms=0",
                        task.taskId(), task.requestId(), workerId, task.taskType(), task.status(), task.retryCount());
            }
            for (AgentTaskRow task : tasks) {
                runOne(task);
            }
        } catch (Exception e) {
            log.warn("[agent-task] event=worker_tick_failed worker_id={} err={}", workerId, e.toString());
        }
    }

    private void runOne(AgentTaskRow task) {
        long startNs = System.nanoTime();
        String previousRequestId = MDC.get("requestId");
        if (task.requestId() != null && !task.requestId().isBlank()) {
            MDC.put("requestId", task.requestId());
        }
        try {
            log.info("[agent-task] event=task_started task_id={} request_id={} worker_id={} task_type={} status={} retry_count={} latency_ms=0",
                    task.taskId(), task.requestId(), workerId, task.taskType(), task.status(), task.retryCount());
            if (task.taskType() != AgentTaskType.ANALYSIS_REPORT_MOCK) {
                throw new IllegalArgumentException("unsupported task_type: " + task.taskType());
            }
            ObjectNode result = objectMapper.createObjectNode();
            result.put("report_type", AgentTaskType.ANALYSIS_REPORT_MOCK.name());
            result.put("title", "Mock Financial Analysis Report");
            result.put("summary", "This is a mock async report generated by Async Agent Task V1.");
            result.set("input_payload", task.payload());
            result.put("generated_at", Instant.now().toString());
            result.put("non_investment_advice", true);
            result.put("risk_disclaimer", "仅供研究和教育参考，不构成投资建议。");
            result.put("mock_data", true);
            result.put("real_financial_api_used", false);
            result.put("trading_capability_used", false);
            long latencyMs = elapsedMs(startNs);
            repository.markSucceeded(task.taskId(), result, workerId, latencyMs);
            log.info("[agent-task] event=task_succeeded task_id={} request_id={} worker_id={} task_type={} status=SUCCEEDED retry_count={} latency_ms={}",
                    task.taskId(), task.requestId(), workerId, task.taskType(), task.retryCount(), latencyMs);
        } catch (Exception e) {
            long latencyMs = elapsedMs(startNs);
            AgentTaskRow updated = repository.markFailedOrRetry(task.taskId(), e.toString(), workerId, latencyMs)
                    .orElse(task);
            log.warn("[agent-task] event=task_failed_or_retry task_id={} request_id={} worker_id={} task_type={} status={} retry_count={} latency_ms={} err={}",
                    task.taskId(), task.requestId(), workerId, task.taskType(), updated.status(), updated.retryCount(), latencyMs, e.toString());
        } finally {
            if (previousRequestId != null && !previousRequestId.isBlank()) {
                MDC.put("requestId", previousRequestId);
            } else {
                MDC.remove("requestId");
            }
        }
    }

    private static long elapsedMs(long startNs) {
        return (System.nanoTime() - startNs) / 1_000_000L;
    }

    private static String buildWorkerId() {
        String host = "unknown";
        try {
            host = InetAddress.getLocalHost().getHostName();
        } catch (Exception ignored) {
        }
        return host + ":" + ManagementFactory.getRuntimeMXBean().getName() + ":" + UUID.randomUUID();
    }
}
